7 février 2020 09:17:38	System.Exception: The request to the API failed. ---> System.Net.Http.HttpRequestException: Une erreur s'est produite lors de l'envoi de la demande. ---> System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:80
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   à System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__8.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 97
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__8.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 102
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CallSite.Target(Closure , CallSite , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   à CutQueue.AppContext.<LogInToFabplan>d__17.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\AppContext.cs:ligne 247
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.AppContext.<DoSync>d__12.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\AppContext.cs:ligne 160

7 février 2020 09:23:45	System.Exception: The request to the API failed. ---> System.Net.Http.HttpRequestException: Une erreur s'est produite lors de l'envoi de la demande. ---> System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:80
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   à System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__8.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 97
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__8.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 102
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CallSite.Target(Closure , CallSite , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   à CutQueue.AppContext.<LogInToFabplan>d__17.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\AppContext.cs:ligne 247
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.AppContext.<DoSync>d__12.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\AppContext.cs:ligne 160

7 février 2020 10:07:07	System.Exception: The request to the API failed. ---> System.Net.Http.HttpRequestException: Une erreur s'est produite lors de l'envoi de la demande. ---> System.Net.WebException: Impossible de se connecter au serveur distant ---> System.Net.Sockets.SocketException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée 127.0.0.1:80
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   à System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__8.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 97
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__8.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 102
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à CallSite.Target(Closure , CallSite , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   à CutQueue.AppContext.<LogInToFabplan>d__17.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\AppContext.cs:ligne 247
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.AppContext.<DoSync>d__12.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\AppContext.cs:ligne 160

